sources:
  include:
    - ../../Lingugram
  exclude:
    - ../../Lingugram/Sources/Mocks/SDK
templates:
  - AutoMockable.stencil
output:
  ../../Lingugram/Sources/Mocks/Generated/GeneratedMocks.swift
